Movie Ticket/BoxOffice/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf.urls import url,include
from home.views import ShowIndex, RegisterView, LoginView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$',LoginView.as_view(),name = 'login'),
    url(r'^logout/$',LogoutView.as_view(),name = 'logout'),
    url(r'^$', ShowIndex.as_view()),
    url(r'^search/$', SearchView.as_view(),name='search'),
    url(r'^movies/', include('movie.urls',namespace='movie')),
    url(r'^booking/', include('booking.urls',namespace='booking')),
    url(r'^theatres/', include('theatre.urls',namespace='theatre')),
    url(r'^register/$',RegisterView.as_view(),name='register'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Movie Ticket/booking/urls.py
from django.conf.urls import url
from .views import payment_gateway, payment_confirmation, reserve_seat,BookingListView,BookingDetailView\
,BookingDeleteView
app_name = 'booking'
urlpatterns = [
    url(r'^seatchoice/(?P<show_id>\d+)/$', reserve_seat, name='reserve_seat'),
    url(r'^payment/$', payment_gateway, name='payment_gateway'),
    url(r'^payment_confirmation/$', payment_confirmation, name='payment_confirmation'),
    url(r'^$', BookingListView.as_view(), name='list'),
    url(r'^(?P<btid>.*)/delete/$', BookingDeleteView.as_view(), name='delete')
 ,   url(r'^(?P<btid>.*)/$', BookingDetailView.as_view(), name='detail'),
#    url(r'^(?P<btid>.*)/delete/$', BookingDeleteView.as_view(), name='delete')
]

Movie Ticket/movie/urls.py
from django.conf.urls import url
from .views import MovieListView, movie_details

app_name = 'movie'

urlpatterns = [
    
    url(r'^$', MovieListView.as_view(), name='list'),
    url(r'^(?P<movie_id>\d+)/$', movie_details, name='detail'),
        
]

Movie Ticket/booking/models.py
from django.db import models
from django.contrib.auth import get_user_model
from theatre.models import Show
from django.urls import reverse
from django.db.models.signals import post_delete
User = get_user_model()
# Create your models here.


class Booking(models.Model):
    payment_choice = (
        ('Debit Card', 'Debit Card'),
        ('Credit Card', 'Credit Card'),
        ('Net Banking', 'Net Banking'),
        ('Wallet', 'Wallet'),
    )
    id                =     models.CharField(primary_key=True, max_length=200)
    timestamp         =     models.DateTimeField('%Y-%m-%d %H:%M:%S')
    payment_type      =     models.CharField(max_length=11, choices=payment_choice)
    paid_amount       =     models.DecimalField(max_digits=8, decimal_places=2)
    paid_by           =     models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.id)
    def get_absolute_url(self):
        return reverse('booking:detail',kwargs={'btid':self.id})
    
    #def get_absolute_url(self):

class Seat(models.Model):
    seat_choice = (
        ('', 'Select'),
        ('Silver', 'Silver'),
        ('Gold', 'Gold'),
        ('Platinum', 'Platinum'),
    )
    no              =       models.CharField(max_length=3)
    seat_type       =       models.CharField(max_length=8, choices=seat_choice, blank=False)
    show            =       models.ForeignKey(Show, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('no', 'show')

    def __str__(self):
        return self.no + str(self.show)


class BookedSeat(models.Model):
    seat            =       models.ForeignKey(Seat, on_delete=models.CASCADE)
    booking         =       models.ForeignKey(Booking, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('seat', 'booking')

    def __str__(self):
        return str(self.seat) + '|' + str(self.booking)


def delete_reverse(sender,instance,*args,**kwargs):
    try:
        if instance.seat:
            instance.seat.delete()
    except:
        pass

post_delete.connect(delete_reverse,sender=BookedSeat)

Movie Ticket/booking/forms.py
from django import forms
from .models import Seat, Booking


class SeatForm(forms.ModelForm):

	class Meta:
		model = Seat
		fields = ('seat_type',)


class BookingForm(forms.ModelForm):

	class Meta:
		model = Booking
		fields = ('payment_type',)

Movie Ticket/booking/views.py
from django.shortcuts import render, get_object_or_404
from .models import Booking, BookedSeat, Seat
from theatre.models import Show
from .forms import SeatForm, BookingForm
from django.urls import reverse_lazy
#from django.views.generic import CreateView
import datetime
from django.views.generic import ListView,DetailView,DeleteView
from theatre.models import Theatre
from django.shortcuts import redirect
from django.http.response import Http404

# Create your views here.

def reserve_seat(request, show_id):
    try:
        show_info = Show.objects.get(pk=show_id)
    except Theatre.DoesNotExist:
        raise Http404("Page does not exist")
    form = SeatForm()
    return render(request, 'reserve_seat.html', 
        {'show_info': show_info, 'form': form})


def payment_gateway(request):
    if request.POST:
        seats = request.POST.get('selected_seat')
        seat_type = request.POST.get('seat_type')
        show_id = request.POST.get('show_id')

        show = Show.objects.get(pk=show_id)
        seats = seats.split(',')
        book_seat = []
        for each in seats:
            if Seat.objects.filter(no=each, show=show).exists():
                return render(request, 'reserve_seat.html', 
                    {'show_info': show, 'form': SeatForm()})
            s = Seat(no=each, seat_type=seat_type, show=show)
            book_seat.append(s)
        Seat.objects.bulk_create(book_seat)

        form = BookingForm()

        price_dict = {'Platinum': 300, 'Gold': 200, 'Silver': 100}
        ticket_price = price_dict[seat_type]*len(book_seat)

        seat_str = ""
        for i in range(0, len(seats)):
            if i == len(seats)-1:
                seat_str += seats[i]
            else:
                seat_str += seats[i] + ','

        return render(request, 'payment_gateway.html', 
            {'seats': seat_str, 'seat_type': seat_type, 
            'show': show, 'form': form, 'ticket_price': ticket_price})
    else:
        return redirect('theatre.views.theatre_list')


def payment_confirmation(request):
    if request.POST:
        show_id = request.POST.get('show_id')
        show = Show.objects.get(pk=show_id)
        seats = request.POST.get('selected_seat')
        seats = seats.split(',')
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        payment_type = request.POST.get('payment_type')
        paid_amount = request.POST.get('amount')
        paid_by = request.user
        id = str(show) + str(seats) + timestamp
        book = Booking(id=id, timestamp=timestamp, payment_type=payment_type, 
            paid_amount=paid_amount, paid_by=paid_by)
        book.save()

        booked_seat = []

        for seat in seats:
            print(seat)
            s = Seat.objects.get(no=seat, show=show)
            b = Booking.objects.get(pk=id)
            booked = BookedSeat(seat=s, booking=b)
            booked_seat.append(booked)

        BookedSeat.objects.bulk_create(booked_seat)

        return render(request, 'payment_confirmation.html')
    else:
        return redirect('theatre.views.theatre_list')


class BookingListView(ListView):
    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)
    
class BookingDetailView(DetailView):
    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)
    
    def get_object(self,*args,**kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking,id=btid)
        return obj

class BookingDeleteView(DeleteView):
    model = Booking
    success_url = reverse_lazy('booking:list')    
    def get_object(self,*args,**kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking,id=btid)
        return obj

Movie Ticket/booking/templates/booking/booking_confirm_delete.html
{% extends "base.html" %}

{% block title %}
    BoxOffice | Delete
{% endblock %}

{% block content %}
    
    <form action=""  method="POST">{% csrf_token %}
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
    <p class="text-warning" style="font-size:25px">Are you sure you want to delete"{{ object }}"?</p>
    </div>
    </div>
    <div class="row">
    <div class="col-sm-offset-5 col-sm-6">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" class="btn btn-danger" value="Confirm" />
    </div>
    </div>
    </form>
    
{% endblock %}

Movie Ticket/booking/templates/booking/booking_detail.html
{% extends "base.html" %}

{% block title %}
    BoxOffice | Booking
{% endblock %}

{% block content %}
    <h2>Booking Details</h2>
    <hr /><br /><br />
    <font size=4>
    <div class="row">
    <div class="col-sm-offset-2 col-sm-2">
    <label>Booking ID :- </label>
    </div>
    <div class="col-sm-8">
    {{ object.id }}
    </div>
    </div>
    <br /><br />
    <div class="row">
    <div class="col-sm-offset-2 col-sm-2">
    <label>Date & Time :- </label>
    </div>
    <div class="col-sm-8">
    {{ object.timestamp }}
    </div>
    </div>
    <br /><br />
    <div class="row">
    <div class="col-sm-offset-2 col-sm-2">
    <label>Payment Type :- </label>
    </div>
    <div class="col-sm-8">
    {{ object.payment_type }}
    </div>
    </div>
    <br /><br />
    <div class="row">
    <div class="col-sm-offset-2 col-sm-2">
    <label>Paid Amount :- </label>
    </div>
    <div class="col-sm-8">
    {{ object.paid_amount }}
    </div>
    </div>
    <div class="row">
    <div class="col-sm-offset-2 col-sm-8">
    <center>
    <a href="{% url 'booking:delete' btid=object.id %}" class="btn btn-danger">Delete</a>
    </center>
    </div>
    </div>
    </font>
{% endblock %}

Movie Ticket/booking/templates/booking/booking_list.html
{% extends "base.html" %}

{% block title %}
    BoxOffice | Booking
{% endblock %}

{% block content %}
    
    
    <h2>My Bookings</h2>
    
    
    <hr />
    <br /><br />
    {% if object_list %}
    
    <div class="jumbotron col-sm-offset-1 col-sm-10" style="background-color:#FFE4E1">
    <ul>
    <font size="4">
    
    {% for book in object_list %}
    <li><a href="{{ book.get_absolute_url }}">{{ book }}</a></li>
    <br />
    {% endfor %}
    </font>
    </ul>
    </div>
    
    {% else %}
    <p class="text-center lead">No Bookings to Show</p>
    {% endif %}
{% endblock %}